spring.cloud.stream.default-binder=rabbit
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# --- CONSUMIDOR (Entrada) ---
spring.cloud.stream.rabbit.bindings.persistEmployee-in-0.consumer.exchangeType=topic
spring.cloud.stream.rabbit.bindings.persistEmployee-in-0.consumer.bindingRoutingKey=equipment.assigned
spring.cloud.stream.rabbit.bindings.persistEmployee-in-0.consumer.autoBindDlq=true

# --- PRODUTOR (Saída) ---
spring.cloud.stream.rabbit.bindings.persistEmployee-out-0.producer.exchangeType=topic

# --- A LINHA QUE FALTA ---
spring.cloud.stream.rabbit.bindings.persistEmployee-out-0.producer.routingKeyExpression=headers['my-routing-key']