spring.cloud.function.definition=handleSaveCommand

# --- INPUT (Vem do Maestro, nao mais do Inventory) ---
spring.cloud.stream.bindings.handleSaveCommand-in-0.destination=db-commands
spring.cloud.stream.bindings.handleSaveCommand-in-0.group=db-orchestration-group

# --- OUTPUT (Responde ao Maestro) ---
spring.cloud.stream.bindings.handleSaveCommand-out-0.destination=saga-replies