# Define qual função Java será ativada
spring.cloud.function.definition=persistEmployee

# --- BINDINGS (O Elo Perdido) ---

# INPUT: Ouve o resultado do Inventory (EquipmentAssigned)
spring.cloud.stream.bindings.persistEmployee-in-0.destination=employee-results
spring.cloud.stream.bindings.persistEmployee-in-0.group=db-service-group

# OUTPUT: Manda Sucesso (Approved) ou Erro (Failed)
spring.cloud.stream.bindings.persistEmployee-out-0.destination=employee-results