# DB Service: application-rabbit.properties

spring.cloud.stream.default-binder=rabbit
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# CONSUMIDOR (Entrada)
spring.cloud.stream.rabbit.bindings.persistEmployee-in-0.consumer.exchangeType=topic

# O RabbitMQ NEM ENTREGA a mensagem de erro para o DB. Economiza CPU e evita bugs.
spring.cloud.stream.rabbit.bindings.persistEmployee-in-0.consumer.bindingRoutingKey=salary.validated

spring.cloud.stream.rabbit.bindings.persistEmployee-in-0.consumer.autoBindDlq=true