spring.cloud.function.definition=persistEmployee

# INPUT: Escuta o resultado do Payroll
spring.cloud.stream.bindings.persistEmployee-in-0.destination=employee-results
spring.cloud.stream.bindings.persistEmployee-in-0.group=db-service-group

# OUTPUT: Avisa que salvou (Opcional, mas boa pratica)
spring.cloud.stream.bindings.persistEmployee-out-0.destination=employee-lifecycle