spring.cloud.stream.default-binder=kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092

# --- CONSUMIDOR (Persistencia) ---
spring.cloud.stream.bindings.persistEmployee-in-0.destination=employee-results
spring.cloud.stream.bindings.persistEmployee-in-0.group=db-service-group

# --- PRODUTOR (Resultado Final) ---
spring.cloud.stream.bindings.persistEmployee-out-0.destination=employee-results